name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Setup build environment
      run: |
        sudo apt update
        sudo apt install -y git make bc libssl-dev bison flex libelf-dev cpio binutils

    - name: Restore dtc shipped files
      run: |
        git checkout -- scripts/dtc/dtc-lexer.lex.c_shipped
        git checkout -- scripts/dtc/dtc-parser.tab.c_shipped

    - name: Build kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make merlin_defconfig
        scripts/config --disable LTO_CLANG
        scripts/config --disable THINLTO
        scripts/config --disable MTK_TEE_GP_SUPPORT
        scripts/config --disable MICROTRUST_TEE_SUPPORT
        make -j$(nproc)

    - name: Upload Image.gz-dtb
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb
        path: arch/arm64/boot/Image.gz-dtb
