name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Setup build environment
      run: |
        sudo apt update
        sudo apt install -y git make gcc bc libssl-dev bison flex libelf-dev cpio binutils gcc-aarch64-linux-gnu
        git clone https://git.kernel.org/pub/scm/utils/dtc/dtc.git
        cd dtc
        make
        sudo make install
        cd ..

    - name: Build kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make merlin_defconfig
        scripts/config --disable LTO_CLANG
        scripts/config --disable THINLTO
        make -j$(nproc)
